### ISSUE TITLE
[功能支持]支持qemu-nbd下动态vhd挂载

### ISSUE THREAD

**Issue by lz-lunzi** [NyaMisty/dracut-vdfuseloop#1]
fedora/arch 下无法编译vdfuse 使用qemu-nbd代替方案,
qemu-nbd代替方案代替中出现卡在dract-initqueue timeout check过程中nbd挂载信息丢失
希望可以有成功的qemu-nbd代替方案实现

**Comment by NyaMisty** [comment]
不太可能没法编译vdfuse，大概率是你的问题。
qemu-nbd对大部分格式支持都有问题，没有支持的意义
